# Project Information
site_name: UnityStation
site_description: 'Project Design and Documentation for development'
site_author: 'MrMepper'
site_url: 'https://unitystation.github.io/unitystation/'

# Repository
repo_name: 'unitystation/unitystation'
repo_url: 'https://github.com/unitystation/unitystation/'
edit_uri: 'edit/develop/docs/'

theme:
  name: 'material'
  feature:
    tabs: true
  language: 'en'
  favicon: 'assets/images/favicon.ico'
  logo: 'assets/images/logo.png'
  
markdown_extensions:
  - attr_list
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg