version: "3.7"

services:
  unitystation:
    image: unitystation/unitystation:develop
    ports:
      - 7777:7777
    environment:
      HUB_USERNAME: $HUB_USERNAME
      HUB_PASSWORD: $HUB_PASSWORD
      SERVER_NAME: Unitystation - EU02 Staging
    labels:
      - io.portainer.accesscontrol.public
    volumes:
      - /etc/UnityStation/admin:/Unitystation_Data/StreamingAssets/admin