# Automation actions that run on every push and pr. Meant to help us to keep the thing cool because we're cool like that.

name: Auto helpers
on:
  push:
    branches: [ develop ]
  pull_request_target:
    branches: [ develop ]
    
jobs:
  autohelpers:
    runs-on: ubuntu-latest
    steps:
      - name: conflicts check
        uses: mschilde/auto-label-merge-conflicts@v2.0
        with:
          CONFLICT_LABEL_NAME: "Status: Merge Conflicts"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: auto labeler
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/labeler@v3-preview
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
